# -- Worload
replicaCount: 1

image:
  repository: docker.io/glanceapp/glance
  pullPolicy: IfNotPresent
  tag: ''   # leave empty to use .Chart.AppVersion.

imagePullSecrets: []          # e.g., [{ name: regcred }]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""                    # empty => use fullname

podAnnotations: {}
podLabels: {}

podSecurityContext: {}        # e.g., { fsGroup: 2000 }
securityContext: {}           # e.g.,
#  capabilities:
#    drop: ["ALL"]
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 1000

# -- Networking
service:
  type: ClusterIP
  port: 8080
  annotations: {}

ingress:
  enabled: true
  className: traefik          # or leave empty to omit
  annotations: {}             # e.g., traefik.ingress.kubernetes.io/router.entrypoints: websecure
  tls:                        # optional
    - hosts: ["my.example.com"]
      secretName: glance-tls
  hosts:
    - host: my.example.com
      paths:
        - path: /
          pathType: Prefix

# -- Probes (Deployment uses `with`: omit to disable)
livenessProbe: {}
#  httpGet:
#    path: /api/healthz
#    port: http
readinessProbe: {}
#  httpGet:
#    path: /api/healthz
#    port: http

# -- Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi

# -- Extra volumes/mounts and scheduling knobs
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

# -- Application configuration injected via ConfigMap
config:
  data: |
    pages:
      - name: Home
        # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
        # hide-desktop-navigation: true
        columns:
          - size: small
            widgets:
              - type: calendar
                first-day-of-week: monday

              - type: rss
                limit: 10
                collapse-after: 3
                cache: 12h
                feeds:
                  - url: https://selfh.st/rss/
                    title: selfh.st
                    limit: 4
                  - url: https://ciechanow.ski/atom.xml
                  - url: https://www.joshwcomeau.com/rss.xml
                    title: Josh Comeau
                  - url: https://samwho.dev/rss.xml
                  - url: https://ishadeed.com/feed.xml
                    title: Ahmad Shadeed

              - type: twitch-channels
                channels:
                  - theprimeagen
                  - j_blow
                  - piratesoftware
                  - cohhcarnage
                  - christitustech
                  - EJ_SA

          - size: full
            widgets:
              - type: group
                widgets:
                  - type: hacker-news
                  - type: lobsters

              - type: videos
                channels:
                  - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCsBjURrPoezykLs9EqgamOA # Fireship
                  - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
                  - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

              - type: group
                widgets:
                  - type: reddit
                    subreddit: technology
                    show-thumbnails: true
                  - type: reddit
                    subreddit: selfhosted
                    show-thumbnails: true

          - size: small
            widgets:
              - type: weather
                location: London, United Kingdom
                units: metric # alternatively "imperial"
                hour-format: 12h # alternatively "24h"
                # Optionally hide the location from being displayed in the widget
                # hide-location: true

              - type: markets
                markets:
                  - symbol: SPY
                    name: S&P 500
                  - symbol: BTC-USD
                    name: Bitcoin
                  - symbol: NVDA
                    name: NVIDIA
                  - symbol: AAPL
                    name: Apple
                  - symbol: MSFT
                    name: Microsoft

              - type: releases
                cache: 1d
                # Without authentication the Github API allows for up to 60 requests per hour. You can create a
                # read-only token from your Github account settings and use it here to increase the limit.
                # token: ...
                repositories:
                  - glanceapp/glance
                  - go-gitea/gitea
                  - immich-app/immich
                  - syncthing/syncthing
