apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glance.fullname" . }}-etc
  labels: 
    {{- include "glance.labels" . | nindent 4 }}
data:
  {{- $main := (default "glance.yml" .Values.config.mainFilename) }}
  {{- $data := (default (include "glance.defaultConfig" .) .Values.config.data) }}
  {{ $main }}: |
{{ tpl $data . | indent 4 }}

  # Extra config files that should be mounted literally (no Helm templating)
  {{- range $name, $content := (default (dict) .Values.config.files) }}
  {{ $name }}: |
{{ $content }}
  {{- end }}

  # Optional: files that should be Helm-templated
  {{- range $name, $content := (default (dict) .Values.config.tplFiles) }}
  {{ $name }}: |
{{ tpl $content $ | indent 4 }}
  {{- end }}