replicaCount: 1

ingress:
  enabled: false

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Keep default image (uses appVersion) – OK for public images
# If Docker Hub rate limits ever bite CI, you can override to a GHCR mirror here.

serviceAccount:
  automount: false
