name: Lint and Test Charts

on:
  pull_request:
    branches: [ main ]
    paths:
      - charts/**        # only run when charts change
  push:
    branches: [ main ]
    paths:
      - charts/**

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      # Create a disposable Kubernetes cluster for ct install
      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          version: v0.23.0          # kind
          node_image: kindest/node:v1.29.4

      # Optional: confirm which charts changed (useful in logs)
      - name: List changed charts
        id: list-changed
        run: |
          ct list-changed --config .ct.yaml

      - name: Run chart-testing (lint)
        run: ct lint --config .ct.yaml

      - name: Run chart-testing (install)
        run: ct install --config .ct.yaml
