name: Publish Helm charts (unified index)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - charts/**          # if your charts live at repo root
      - .github/workflows/publish.yaml

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Install yq
        uses: mikefarah/yq@v4.44.3

      # One-time normalization: move any old per-chart packages up
      - name: Normalize docs layout
        run: |
          set -euo pipefail
          mkdir -p docs
          shopt -s nullglob
          for f in docs/*/*.tgz; do
            mv -n "$f" docs/
          done
          rm -f docs/*/index.yaml
          touch docs/.nojekyll

      - name: Lint and package charts
        run: |
          set -euo pipefail
          mkdir -p docs
          shopt -s nullglob
          charts=(charts/*)
          if [ ${#charts[@]} -eq 0 ]; then
            echo "No charts under charts/"; exit 0
          fi

          for chartdir in "${charts[@]}"; do
            [ -d "$chartdir" ] || continue
            echo "::group::Processing $chartdir"
            helm lint "$chartdir"

            NAME="$(yq -r '.name' "$chartdir/Chart.yaml")"
            VERSION="$(yq -r '.version' "$chartdir/Chart.yaml")"
            APPVER="$(yq -r '.appVersion' "$chartdir/Chart.yaml")"
            echo "Chart: $NAME  version: $VERSION  appVersion: $APPVER"

            # Robust: check if this exact chart+version is already in docs/index.yaml
            if [ -f docs/index.yaml ] && yq -e ".entries[\"$NAME\"] | any(.version == \"$VERSION\")" docs/index.yaml >/dev/null 2>&1; then
              echo "Skip packaging: $NAME $VERSION already present in unified index"
            else
              echo "Packaging $NAME $VERSION"
              helm dependency update "$chartdir" || true
              helm package "$chartdir" -d docs
            fi
            echo "::endgroup::"
          done

      - name: Update unified Helm repo index
        run: |
          set -euo pipefail
          URL="https://rphllc.github.io/helm"
          if [ -f docs/index.yaml ]; then
            helm repo index docs --url "$URL" --merge docs/index.yaml
          else
            helm repo index docs --url "$URL"
          fi

      - name: Commit docs to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Publish Helm charts (unified index)"
          branch: main
          file_pattern: docs/**
          push_options: '--force-with-lease'
