name: Publish Helm charts (unified index)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - charts/**

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Install yq
        uses: mikefarah/yq@v4.44.3

      # Optional: normalize legacy layout (one-time safe to keep)
      - name: Move old packaged charts from subfolders into docs/
        run: |
          mkdir -p docs
          shopt -s nullglob
          for f in docs/*/*.tgz; do
            mv -n "$f" docs/
          done
          # Remove per-chart index files if present; they confuse Helm users
          rm -f docs/*/index.yaml

      # Lint & package every chart under charts/* into docs/
      - name: Lint and package charts
        run: |
          set -euo pipefail
          mkdir -p docs
          shopt -s nullglob
          charts=(charts/*)
          if [ ${#charts[@]} -eq 0 ]; then
            echo "No charts found under charts/"; exit 0
          fi

          for chartdir in "${charts[@]}"; do
            [ -d "$chartdir" ] || continue
            echo "::group::Processing $chartdir"
            helm lint "$chartdir"

            # Read chart name/version
            NAME="$(yq -r '.name' "$chartdir/Chart.yaml")"
            VERSION="$(yq -r '.version' "$chartdir/Chart.yaml")"

            # Skip packaging if same version is already in unified docs/index.yaml
            if [ -f docs/index.yaml ] && grep -q "name: $NAME" docs/index.yaml && grep -q "version: $VERSION" docs/index.yaml; then
              echo "Skip: $NAME $VERSION already in docs/index.yaml"
            else
              echo "Packaging $NAME $VERSION"
              helm dependency update "$chartdir" || true
              helm package "$chartdir" -d docs
            fi
            echo "::endgroup::"
          done

      # Rebuild ONE unified index at docs/index.yaml
      - name: Update unified Helm repo index (GitHub Pages)
        run: |
          set -euo pipefail
          URL="https://rphllc.github.io/helm"
          if [ -f docs/index.yaml ]; then
            helm repo index docs --url "$URL" --merge docs/index.yaml
          else
            helm repo index docs --url "$URL"
          fi
          touch docs/.nojekyll

      - name: Commit docs to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Publish Helm charts (unified index)"
          branch: main
          file_pattern: docs/**
          push_options: '--force-with-lease'
